/**
 * Rótulos originais dos campos do formulário público de Briefing (BriefingPublicPage.tsx),
 * na ordem em que aparecem no form. Usado pelo editor de modelo (BriefingTemplateModal)
 * pra listar os campos que podem ganhar um override de rótulo — o texto aqui É a chave
 * (briefing_field_overrides.field_key), não um id separado, então precisa bater exatamente
 * com o texto passado pra L('...') em BriefingPublicPage.tsx.
 */
export const BRIEFING_FIELD_LABELS: string[] = [
  'Site da empresa',
  'Nome',
  'E-mail',
  'Setor(es)',
  'Perfil',
  'Fuso horário',
  'Número(s) que vamos conectar',
  'E-mail do Facebook / Meta *',
  'Senha do Facebook / Meta *',
  'Nome do portfólio empresarial (Meta) — opcional',
  'Número dedicado à API Oficial *',
  'Nome que aparecerá no WhatsApp (para os clientes verem) *',
  'Verificação do negócio (Meta)',
  'Acesso de parceiro (partner access)',
  'Informações da conta WaVoip',
  'E-mail / usuário de acesso',
  'Senha de acesso',
  'Outras informações (opcional)',
  'Configurações de e-mail',
  'Resumo do atendimento *',
  'Dados que o bot deve coletar antes de transferir (um por linha)',
  'Mensagem de encerramento',
  'Nome da IA (ex: Ana, Max, Bia) *',
  'Tom de comunicação',
  'Descreva o que a empresa faz e para quem atende *',
  'Localização (cidade, estado ou região de atendimento)',
  'Redes sociais (Instagram, Facebook, TikTok…)',
  'Liste os principais serviços/produtos *',
  'Informe a tabela de preços',
  'Como a IA deve conduzir a conversa? *',
  'Quando a IA deve transferir para um atendente humano? *',
  'O que a IA NÃO deve fazer ou dizer?',
  'O que a IA responde quando NÃO souber algo?',
  'Endereço de cada unidade (com ponto de referência)',
  'Frase ou bordão da empresa que a IA deva usar',
  'Serviços/produtos mais procurados',
  'Convênios, planos ou parcerias (e o que cobrem)',
  'Formas de pagamento (dinheiro, PIX, cartão, parcelamento)',
  'Promoções ou condições especiais',
  'Mensagem que a IA manda no PRIMEIRO contato',
  'Quais dados a IA deve pedir para agendar?',
  'Mensagem depois que o cliente passa os dados',
  'O que a IA faz quando é um cliente que já é atendido por vocês?',
  'Perguntas frequentes dos clientes (pergunta + resposta certa)',
  'Qual sistema será integrado? (nome do sistema)',
  'O que a IA precisa consultar neste sistema? *',
  'URL da API ou webhook (se já tiver)',
  'Como autenticar na API? (token, usuário/senha, chave…)',
  'Descreva exemplos de situações em que a IA consultaria o sistema',
  'Informações necessárias para a automação *',
  'Algo mais que devemos saber?',
]
